---
title: "Ch10_multinomial"
author: "paul"
date: "9/29/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(Lahman)
library(ggplot2)
theme_set(hrbrthemes::theme_ipsum())
```

```{r}
# Identify those who have pitched at least three games
pitchers <- Pitching %>%
  group_by(playerID) %>%
  summarize(gamesPitched = sum(G)) %>%
  filter(gamesPitched > 3)

player_names <- Master %>% 
  transmute(playerID, name = paste(nameFirst, nameLast))

hit_types <- Batting %>%
  filter(AB > 0)%>%
  anti_join(pitchers, by = "playerID") %>% 
  rename(Double = X2B, Triple = X3B) %>% 
  group_by(playerID) %>% 
  summarise_each(funs(sum(., na.rm = TRUE)), AB, H, Double, Triple, HR) %>% 
  inner_join(player_names, by = "playerID") %>% 
  transmute(
    playerID, name, AB, H,
    Single = H - Double - Triple - HR,
    Double, Triple, HR,
    NonHit = AB - H,
    slugging = (Single + 2 * Double + 3 * Triple + 4 * HR) / AB
            )
```
```{r}
hit_types %>% 
  arrange(-slugging) %>% 
  head()
```
Pretty Bad, no shrinkage, no prior

## Multinomial Distribution
```{r}
rmultinom(3,100, rep(.2, times = 5))
```
```{r}
rdiric <- VGAM::rdiric
```
```{r}
rdiric(3, c(1,1,1,1,1))
```

```{r}
hit_500 <- hit_types %>% 
  filter(AB>500)

hit_matrix <- hit_500 %>% 
  select(Single:NonHit) %>% 
  as.matrix()
```

```{r}
dm_fit <- DirichletMultinomial::dmn(hit_matrix, 1)
```

```{r}
library(broom)


```
```{r}
ret <- as.data.frame(dm_fit@fit)
```

```{r}
tidy.DMN <- function(x,...){
  ret <- as.data.frame(x@fit)
  tbl_df(fix_data_frame(ret, c("conf.low", "estimate", "conf.high")))
}
```

```{r}
dm_params <- tidy(dm_fit)
```
```{r}
hit_density <- dm_params %>% 
  mutate(alpha = estimate,
         beta = sum(estimate) - estimate
         ) %>% 
  filter(term != "NonHit") %>% 
  select(type = term, alpha, beta) %>% 
  crossing(x = seq(0, 0.35, length.out = 100)) %>% 
  mutate(density = dbeta(x, alpha, beta))
```
```{r}
hit_types %>% 
  filter(AB>500) %>% 
  mutate_at(vars(Single:NonHit), ~ .x / AB) %>% 
  pivot_longer(Single:NonHit, names_to = "type", values_to = "value") %>% 
  ggplot(aes(value))+
  geom_histogram(aes(y = ..density..))+
  geom_line(data = hit_density, aes(y = density, x = x), color = "red")+
  hrbrthemes::scale_x_percent(limits = c(0, 0.35))+
  facet_wrap(~type)+
  NULL
```
```{r}

eb_AB <- sum(dm_params$estimate)

eb_career <- dm_params %>% 
  select(term, estimate) %>% 
  pivot_wider(names_prefix = "eb_",names_from = term, values_from = estimate) %>% 
  crossing(hit_types) %>%
  mutate(Single = Single + eb_Single,
         Double = Double + eb_Double,
         Triple = Triple + eb_Triple,
         HR = HR + eb_HR,
         NonHit = NonHit + eb_NonHit, 
         AB = AB + eb_AB         
         ) %>% 
  mutate(eb_slugging = (Single + 2 * Double + 3 * Triple + 4 * HR) / AB)
```

```{r}
eb_career %>% 
  filter(AB>3) %>% 
  ggplot(aes(slugging, eb_slugging))+
  geom_point(aes(color = AB))+
  geom_abline(color = "red")+
  scale_color_continuous(trans = "log10")+
  NULL
```

```{r}
eb_career %>% 
  arrange(eb_slugging) %>% 
  View()
```

