---
title: "Ch7_Beta_binom_regression"
author: "paul"
date: "9/22/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(Lahman)
theme_set(theme_light())
library(rlang)
```

```{r}
pitchers <- Pitching %>%
  group_by(playerID) %>%
  summarize(gamesPitched = sum(G)) %>%
  filter(gamesPitched > 3)
career <- Batting %>%
  filter(AB > 0) %>%
  anti_join(pitchers, by = "playerID") %>%
  group_by(playerID) %>%
  summarize(H = sum(H), AB = sum(AB)) %>%
  mutate(average = H / AB)
# add player names
career <- Master %>%
  tbl_df() %>%
  dplyr::select(playerID, nameFirst, nameLast) %>%
  unite(name, nameFirst, nameLast, sep = " ") %>%
  inner_join(career, by = "playerID")

# values estimated by maximum likelihood in Chapter 3
alpha0 <- 101.4
beta0 <- 287.3
prior_mu <- alpha0 / (alpha0 + beta0)
# for each player, update the beta prior based on the evidence
# to get posterior parameters alpha1 and beta1
career_eb <- career %>%
  mutate(eb_estimate = (H + alpha0) / (AB + alpha0 + beta0))%>%
  mutate(alpha1 = H + alpha0,beta1 = AB - H + beta0) %>%
  arrange(desc(eb_estimate))
```

```{r}
career_eb %>% 
  ggplot(aes(AB, average))+
  scale_x_log10()+
  geom_point()+
  geom_smooth(method = "lm", color = "red")
  NULL
```
```{r}
career_eb %>% 
  pivot_longer(c(average, eb_estimate), "type", values_to = "average") %>% 
  ggplot(aes(AB, average))+
  scale_x_log10()+
  geom_point()+
  geom_smooth(method = "lm", color = "red")+
  facet_wrap(~type)+
  NULL
```
the binomial regression shrinks the low AB averages too hard to the prior!
Higher AB players stays the same because they got more time to prove themselves. 

we risk overestimating the ability of lower AB players!
```{r}
library(gamlss)
fit <- gamlss(cbind(H, AB-H) ~ log(AB),
              data = career_eb,
              family = BB(mu.link = "identity")
              )
```
```{r}
library(broom)

td <- tidy(fit)
td
```
```{r}
link <- function(.fit){
  function(AB){
    list(mu = .fit$estimate[1:2] %*% c(1, log(AB)),
         sigma = exp(.fit$estimate[[3]])
        )
    
  }
}
link_fit <- link(td)
link_fit(10000)
```
```{r}
make_curve <- function(ABs, .fit){
  link_fit <- link(.fit)
  funs <- expr(ggplot(data.frame(x = c(0.05,0.35)), aes(x)))
  for (AB in ABs){
    tmp <- link_fit(AB)
    mu <- tmp$mu
    sigma <- tmp$sigma
    new_expr = expr(stat_function(fun = ~dnorm(.x, !!mu, !!sigma)))
    funs <- expr(!!funs + !!new_expr)
  }
  eval(funs)
  # p
}

make_curve(c(1, 10, 100, 1000, 10000),td)
```
```{r}
ggplot(data.frame(x = c(0.05,0.35)), aes(x))+
  stat_function(fun = ~dnorm(.x, 0.283161637687498, 0.00182648861202421))+
  stat_function(fun = ~dnorm(.x, 0.247999767923286, 0.00182648861202421))+
  NULL
```
```{r}
mu_0 <- td$estimate[1]
mu_AB <- td$estimate[2]
sigma <- exp(td$estimate[3])
crossing(x = seq(0.08, .35, .001), AB = c(1, 10, 100, 1000, 10000)) %>%
  mutate(density = dbeta(x, (mu_0 + mu_AB * log(AB)) / sigma,
                         (1 - (mu_0 + mu_AB * log(AB))) / sigma)) %>%
  mutate(AB = factor(AB)) %>%
  ggplot(aes(x, density, color = AB)) +
  geom_line() +
  xlab("Batting average") +
  ylab("Prior density")
```

```{r}
plot(fit)
```
```{r}
fitted_mu <- fitted(fit, parameter = "mu")
fitted_sigma <- fitted(fit, parameter = "sigma")
tmp <- fitted(fit)
```
```{r}
View(tmp)
```
```{r}
career_bb <- career_eb %>% 
  mutate(
    alpha2_prior = fitted_mu / fitted_sigma,
    beta2_prior = (1-fitted_mu)/fitted_sigma,
    alpha2_post = alpha2_prior + H,
    beta2_post = beta2_prior - H + AB,
    bb_estimate = alpha2_post / (alpha2_post + beta2_post)
  )
```
```{r}
career_bb %>% 
  pivot_longer(c(average, eb_estimate, bb_estimate), names_to = "type", values_to = "estimate") %>% 
  mutate(type = as_factor(type) ) %>% 
  ggplot(aes(log(AB), estimate))+
  geom_point()+
  facet_wrap(~type)+
  geom_smooth(method = lm)
  NULL
```
```{r}
career_bb %>% 
  ggplot(aes(eb_estimate, bb_estimate, color = AB))+
  scale_color_continuous(trans = "log")+
  geom_point()+
  geom_abline(slope = 1, intercept = 0)+
  NULL
```

